# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("db_host") %>
  username: <%= ENV.fetch("db_username") %>
  password: <%= ENV.fetch("db_password") %>
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
